name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y gcc g++

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Install SFML
      run: |
        sudo apt-get install -y libsfml-dev

    - name: Install GoogleTest
      run: sudo apt-get install -y libgtest-dev

    - name: Configure CMake
      run: mkdir -p build && cd build && cmake ..

    - name: Build the project
      run: cd build && make

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Configure CMake
      run: sudo mkdir -p test/build && cd test/build && cmake ..

    - name: Run tests
      run: cd /tests/build && ./runTests

