name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y gcc g++

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Install SFML
      run: sudo apt-get install -y libsfml-dev

    - name: Install GoogleTest
      run: sudo apt-get install -y libgtest-dev

    - name: Configure CMake
      run: mkdir -p build && cd build && cmake ..

    - name: Build the project
      run: cd build && make

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Install SFML
      run: sudo apt-get install -y libsfml-dev

    - name: Install GoogleTest
      run: sudo apt-get install -y libgtest-dev

    - name: Configure CMake for Tests
      run: cd test/ && mkdir build && cd build && cmake ..

    - name: Build Test
      run: cd test/build && make
      
    - name: Run tests with Xvfb
      run: |
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        cd test/build
        ./runTests
