name: CI

on:
  push:
    branches:
      - main

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SFML
      run: sudo apt-get install -y libsfml-dev

    - name: Install GoogleTest
      run: sudo apt-get install -y libgtest-dev

    - name: Configure CMake
      run: cd test/ && mkdir build && cd build && cmake ..

    - name: Build and Run Tests
      run: cd test/build && make && ./runTests
